import type { Device } from "./types";

const phoneBezel = (radius = 42) => ({
  radius,
  thickness: 10,
  color: "#0a0a0e",
});

const holePunchCenter = (diameter = 24, topOffsetPx = 12) =>
  ({
    kind: "hole-punch" as const,
    diameterPx: diameter,
    position: "top-center" as const,
    topOffsetPx,
  });

const androidGestureBar = {
  kind: "home-indicator" as const,
  widthPx: 108,
  heightPx: 4,
  bottomOffsetPx: 8,
};

export const androids: Device[] = [
  // Pixels
  {
    id: "pixel-7",
    name: "Pixel 7",
    brand: "Google",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 2.625,
    bezel: phoneBezel(48),
    safeArea: { top: 40, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "pixel-8",
    name: "Pixel 8",
    brand: "Google",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 2.625,
    bezel: phoneBezel(48),
    safeArea: { top: 40, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "pixel-8-pro",
    name: "Pixel 8 Pro",
    brand: "Google",
    category: "phone",
    viewport: { width: 448, height: 998 },
    dpr: 3,
    bezel: phoneBezel(52),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(26), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "pixel-9",
    name: "Pixel 9",
    brand: "Google",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 2.625,
    bezel: phoneBezel(50),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "pixel-9-pro",
    name: "Pixel 9 Pro",
    brand: "Google",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 3,
    bezel: phoneBezel(50),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "pixel-9-pro-xl",
    name: "Pixel 9 Pro XL",
    brand: "Google",
    category: "phone",
    viewport: { width: 448, height: 998 },
    dpr: 3,
    bezel: phoneBezel(52),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(26), androidGestureBar],
    supportsRotation: true,
  },

  // Samsung
  {
    id: "galaxy-s23",
    name: "Galaxy S23",
    brand: "Samsung",
    category: "phone",
    viewport: { width: 360, height: 780 },
    dpr: 3,
    bezel: phoneBezel(46),
    safeArea: { top: 40, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "galaxy-s24",
    name: "Galaxy S24",
    brand: "Samsung",
    category: "phone",
    viewport: { width: 360, height: 780 },
    dpr: 3,
    bezel: phoneBezel(46),
    safeArea: { top: 40, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "galaxy-s24-ultra",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 3.5,
    bezel: phoneBezel(32),
    safeArea: { top: 40, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "galaxy-s25",
    name: "Galaxy S25",
    brand: "Samsung",
    category: "phone",
    viewport: { width: 360, height: 780 },
    dpr: 3,
    bezel: phoneBezel(48),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
  {
    id: "galaxy-s25-ultra",
    name: "Galaxy S25 Ultra",
    brand: "Samsung",
    category: "phone",
    viewport: { width: 412, height: 915 },
    dpr: 3.5,
    bezel: phoneBezel(38),
    safeArea: { top: 44, right: 0, bottom: 24, left: 0 },
    features: [holePunchCenter(), androidGestureBar],
    supportsRotation: true,
  },
];
