import type { Device } from "./types";

const bezel = (radius = 54) => ({
  radius,
  thickness: 12,
  color: "#0a0a0e",
});

const island = {
  kind: "dynamic-island" as const,
  widthPx: 125,
  heightPx: 37,
  topOffsetPx: 11,
};

const homeIndicator = {
  kind: "home-indicator" as const,
  widthPx: 134,
  heightPx: 5,
  bottomOffsetPx: 8,
};

const notch = {
  kind: "notch" as const,
  widthPx: 210,
  heightPx: 30,
  radius: 20,
};

export const iphones: Device[] = [
  {
    id: "iphone-se-3",
    name: "iPhone SE (3rd gen)",
    brand: "Apple",
    category: "phone",
    viewport: { width: 375, height: 667 },
    dpr: 2,
    bezel: { radius: 24, thickness: 56, color: "#0a0a0e" },
    safeArea: { top: 20, right: 0, bottom: 0, left: 0 },
    features: [],
    supportsRotation: true,
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    brand: "Apple",
    category: "phone",
    viewport: { width: 390, height: 844 },
    dpr: 3,
    bezel: bezel(),
    safeArea: { top: 47, right: 0, bottom: 34, left: 0 },
    features: [notch, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    brand: "Apple",
    category: "phone",
    viewport: { width: 390, height: 844 },
    dpr: 3,
    bezel: bezel(),
    safeArea: { top: 47, right: 0, bottom: 34, left: 0 },
    features: [notch, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    brand: "Apple",
    category: "phone",
    viewport: { width: 393, height: 852 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 59, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    category: "phone",
    viewport: { width: 393, height: 852 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 59, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "phone",
    viewport: { width: 393, height: 852 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 59, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    category: "phone",
    viewport: { width: 430, height: 932 },
    dpr: 3,
    bezel: bezel(58),
    safeArea: { top: 59, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    brand: "Apple",
    category: "phone",
    viewport: { width: 393, height: 852 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 59, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    brand: "Apple",
    category: "phone",
    viewport: { width: 402, height: 874 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    brand: "Apple",
    category: "phone",
    viewport: { width: 440, height: 956 },
    dpr: 3,
    bezel: bezel(58),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    brand: "Apple",
    category: "phone",
    viewport: { width: 402, height: 874 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-17-air",
    name: "iPhone Air",
    brand: "Apple",
    category: "phone",
    viewport: { width: 413, height: 913 },
    dpr: 3,
    bezel: bezel(56),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    brand: "Apple",
    category: "phone",
    viewport: { width: 402, height: 874 },
    dpr: 3,
    bezel: bezel(55),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    brand: "Apple",
    category: "phone",
    viewport: { width: 440, height: 956 },
    dpr: 3,
    bezel: bezel(58),
    safeArea: { top: 62, right: 0, bottom: 34, left: 0 },
    features: [island, homeIndicator],
    supportsRotation: true,
  },
];
